#!/usr/bin/env python3
"""bin2h.py — embed a binary file as a C array header.

Usage:
    python bin2h.py <input.bin> <symbol_name> <output.h> [--slice START LEN]

Emits a `const unsigned char <symbol_name>[] = {...};` plus a
`const unsigned <symbol_name>_len = N;`. With --slice, embeds only LEN bytes
starting at offset START (used to split the 32KB 128K ROM into its two 16KB
banks). Keeps the repo free of committed binaries: run this at need / in a
build step. See reference/ROMS.md for provenance.
"""
import sys

def main():
    args = sys.argv[1:]
    start, length = 0, None
    if "--slice" in args:
        i = args.index("--slice")
        start = int(args[i + 1], 0)
        length = int(args[i + 2], 0)
        del args[i:i + 3]
    if len(args) != 3:
        print(__doc__)
        sys.exit(1)
    inp, sym, out = args

    with open(inp, "rb") as f:
        data = f.read()
    if length is not None:
        data = data[start:start + length]

    lines = [
        f"// Auto-generated by tools/bin2h.py from {inp}",
        f"// {len(data)} bytes. Do not edit by hand.",
        "#pragma once",
        f"const unsigned {sym}_len = {len(data)};",
        f"const unsigned char {sym}[] = {{",
    ]
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append("    " + "".join(f"0x{b:02x}," for b in chunk))
    lines.append("};")
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {out}: {len(data)} bytes as {sym}[]")

if __name__ == "__main__":
    main()
