#pragma once

// Output mode enums
enum CVOutMode { CVOUT_ARP=0, CVOUT_ROOT, CVOUT_RES_ENV, CVOUT_IN_ENV, CVOUT_RANDOM_SH, CVOUT_PITCH_SH, CVOUT_PITCH_TRACK };
enum P1Mode   { P1_AUDIO_TRIG=0, P1_TAP_CLOCK, P1_ARP_CLOCK, P1_ONSET };
enum P2Mode   { P2_CHORD_TRIG=0, P2_TAP_CLOCK, P2_AUDIO_TRIG, P2_ARP_CLOCK, P2_CLK_DIV, P2_ONSET };
enum PI1Mode  { PI1_PLUCK=0, PI1_ADVANCE, PI1_RESET };
enum PI2Mode  { PI2_ADVANCE=0, PI2_ARP_STEP, PI2_PLUCK, PI2_RESET };
enum AO2Mode  { AO2_AUDIO=0, AO2_RES_ENV, AO2_IN_ENV };
enum CI1Mode  { CI1_VOCT=0, CI1_ARP_ONLY };
enum CI2Mode  { CI2_DAMPING=0, CI2_MIX };
